org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,OBSOLETE_API
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=true
kotlin_version=2.4.10
# Allow project-level repositories (needed for Flutter plugin loader)
org.gradle.configuration-cache=false
kotlin.incremental=false
